# Generated by Django 4.2.30 on 2026-05-25 18:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0004_comment_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="bookmarked",
            field=models.ManyToManyField(
                blank=True, related_name="bookmarked_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
